### PR TITLE
chore: update github actions

### PR DESCRIPTION
**Pull request by maximousblk**
- added release notes generator
- fix artifact names in installers
- update npm scripts

### CODE REVIEW

**Comment by maximousblk** [comment]
do not merge yet

**Review by johnletey — COMMENTED** [review]
@maximousblk Just want to note that you have put `LICENCE` instead of `LICENSE` when creating the release zips 😄

**Comment by maximousblk** [comment]
sorting an issue with the build process

**Comment by maximousblk** [comment]
fixed!

**Review by divy-work — APPROVED** [review]
Awesome! LGTM

**Pull request merged**
