### PR TITLE
feat: add upgrade subcommand

### LINKED ISSUE #15: `verto upgrade`
Add subcommand update to trigger the installer and update the binaries.

### PR DESCRIPTION
**Pull request by divy-work**
Add `verto upgrade` - triggers installers

Closes #15 

**Note**: the command won't work until we release :smile: (tested with @maximousblk's release fork)

### CODE REVIEW

**Review by johnletey — APPROVED** [review]
LGTM @divy-work. I assume it works lol 😆

**Comment by divy-work** [comment]
hehe it does with max's fork release :) so it will work when we release too!

**Review by t8 — APPROVED** [review]
LGTM!

**Review by maximousblk — APPROVED** [review]
LGTM

**Pull request merged**
